# Generated by Django 4.0.2 on 2022-03-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_location_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Place',
        ),
    ]
